language: java
sudo: false
install: true

jdk:
  - oraclejdk8

env:
  - secure: env.SONAR_TOKEN

script:
  - echo "env.SONAR_TOKEN"
  - echo "${SONAR_TOKEN}"
  - mvn clean package sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'