language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "shaburov-github"
    token:
      secure: env.SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'